# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _spdiags_kernel(
    diagonals_ptr,
    offsets_ptr,
    indices_row_ptr,
    indices_col_ptr,
    values_ptr,
    nnz_offsets_ptr,
    num_diags: tl.constexpr,
    diag_len: tl.constexpr,
    nrows: tl.constexpr,
    ncols: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Kernel to compute sparse COO indices and values from diagonals.
    Each program processes one block of one diagonal.
    """
    pid = tl.program_id(0)
    diag_idx = pid // tl.cdiv(diag_len, BLOCK_SIZE)
    block_idx = pid % tl.cdiv(diag_len, BLOCK_SIZE)

    if diag_idx >= num_diags:
        return

    # Load offset for this diagonal
    offset = tl.load(offsets_ptr + diag_idx).to(tl.int32)

    # Compute base position
    base_pos = block_idx * BLOCK_SIZE
    positions = base_pos + tl.arange(0, BLOCK_SIZE)

    # PyTorch's _spdiags semantics:
    # - For offset >= 0: skip first k elements, use diagonal[k:], place at (0,k), (1,k+1), ...
    # - For offset < 0: use diagonal[0:], place at (|k|,0), (|k|+1,1), ..., limited by matrix bounds
    #
    # Diagonal value index:
    # - offset >= 0: read from diagonal[k + position]
    # - offset < 0: read from diagonal[position]

    # Index into the diagonal array
    diag_val_idx = tl.where(offset >= 0, positions + offset, positions)

    # Matrix row and column indices
    raw_row_idx = tl.where(offset >= 0, positions, positions - offset)
    raw_col_idx = tl.where(offset >= 0, positions + offset, positions)

    # Apply row-major indexing adjustment for out-of-bounds column indices
    # This matches PyTorch CPU's behavior: (r, c) where c >= ncols becomes (r + c//ncols, c%ncols)
    col_overflow = raw_col_idx // ncols
    row_idx = raw_row_idx + col_overflow
    col_idx = raw_col_idx % ncols

    # Check validity: diagonal value exists AND adjusted indices are in bounds
    valid = (
        (diag_val_idx < diag_len)
        & (row_idx >= 0)
        & (row_idx < nrows)
        & (col_idx >= 0)
        & (col_idx < ncols)
    )

    # Load base offset for this diagonal's output
    nnz_base = tl.load(nnz_offsets_ptr + diag_idx).to(tl.int64)

    # Compute output position
    out_idx = nnz_base + positions.to(tl.int64)

    # Load diagonal values
    diag_base = diag_idx * diag_len
    vals = tl.load(diagonals_ptr + diag_base + diag_val_idx, mask=valid, other=0.0)

    # Store indices and values
    tl.store(indices_row_ptr + out_idx, row_idx.to(tl.int64), mask=valid)
    tl.store(indices_col_ptr + out_idx, col_idx.to(tl.int64), mask=valid)
    tl.store(values_ptr + out_idx, vals, mask=valid)


def _spdiags(diagonals, offsets, shape, layout=None):
    """
    Create a sparse diagonal matrix from diagonals.

    Args:
        diagonals: Tensor of shape (num_diags, diag_len) containing diagonal values
        offsets: Tensor of shape (num_diags,) containing diagonal offsets
        shape: List[int] of length 2, the output matrix shape
        layout: Optional layout (only sparse_coo supported)

    Returns:
        Sparse COO tensor
    """
    logger.debug("GEMS _SPDIAGS")

    if layout is not None and layout != torch.sparse_coo:
        raise RuntimeError(
            f"_spdiags only supports sparse_coo layout, but got {layout}"
        )

    if diagonals.dim() != 2:
        raise RuntimeError(
            f"_spdiags: diagonals must be 2-D, but got {diagonals.dim()}-D"
        )

    if offsets.dim() != 1:
        raise RuntimeError(f"_spdiags: offsets must be 1-D, but got {offsets.dim()}-D")

    if len(shape) != 2:
        raise RuntimeError(f"_spdiags: shape must have length 2, but got {len(shape)}")

    num_diags = diagonals.shape[0]
    diag_len = diagonals.shape[1]
    nrows, ncols = shape

    if offsets.shape[0] != num_diags:
        raise RuntimeError(
            f"_spdiags: number of diagonals ({num_diags}) must match "
            f"number of offsets ({offsets.shape[0]})"
        )

    # Handle empty case
    if num_diags == 0 or diag_len == 0 or nrows == 0 or ncols == 0:
        indices = torch.empty((2, 0), dtype=torch.int64, device=diagonals.device)
        values = torch.empty((0,), dtype=diagonals.dtype, device=diagonals.device)
        return torch.sparse_coo_tensor(
            indices, values, size=shape, dtype=diagonals.dtype, device=diagonals.device
        )

    # Use CPU fallback for non-CUDA devices
    if diagonals.device.type != "cuda":
        # Move to CPU, compute, then move back
        diagonals_cpu = diagonals.cpu()
        offsets_cpu = offsets.cpu()
        result_cpu = torch.ops.aten._spdiags.default(
            diagonals_cpu, offsets_cpu, shape, layout
        )
        # Sparse tensors need special handling to move to device
        indices = result_cpu.indices().to(diagonals.device)
        values = result_cpu.values().to(diagonals.device)
        return torch.sparse_coo_tensor(
            indices, values, size=shape, dtype=diagonals.dtype, device=diagonals.device
        )

    # Compute actual nnz for each diagonal
    offsets_cpu = offsets.cpu()
    nnz_per_diag = []
    nnz_offsets = [0]  # Cumulative offsets

    for i in range(num_diags):
        offset_val = int(offsets_cpu[i])

        # Count elements after row-major indexing adjustment
        # For each position in the diagonal, compute the adjusted indices and check bounds
        count = 0
        if offset_val >= 0:
            # Upper diagonal: positions 0, 1, 2, ... map to (0, offset), (1, offset+1), ...
            for pos in range(diag_len - offset_val):
                raw_row = pos
                raw_col = pos + offset_val
                adj_row = raw_row + (raw_col // ncols)
                adj_col = raw_col % ncols
                if adj_row < nrows and adj_col < ncols:
                    count += 1
        else:
            # Lower diagonal: positions 0, 1, 2, ... map to (-offset, 0), (-offset+1, 1), ...
            for pos in range(diag_len + offset_val):
                raw_row = pos - offset_val
                raw_col = pos
                adj_row = raw_row + (raw_col // ncols)
                adj_col = raw_col % ncols
                if adj_row < nrows and adj_col < ncols:
                    count += 1

        nnz_per_diag.append(count)
        nnz_offsets.append(
            nnz_offsets[-1] + diag_len
        )  # Allocate full diag_len per diagonal

    total_nnz = sum(nnz_per_diag)
    if total_nnz == 0:
        indices = torch.empty((2, 0), dtype=torch.int64, device=diagonals.device)
        values = torch.empty((0,), dtype=diagonals.dtype, device=diagonals.device)
        return torch.sparse_coo_tensor(
            indices, values, size=shape, dtype=diagonals.dtype, device=diagonals.device
        )

    # Allocate output buffers (over-allocate to simplify kernel)
    max_buffer_size = num_diags * diag_len
    indices_row_buffer = torch.empty(
        (max_buffer_size,), dtype=torch.int64, device=diagonals.device
    )
    indices_col_buffer = torch.empty(
        (max_buffer_size,), dtype=torch.int64, device=diagonals.device
    )
    values_buffer = torch.empty(
        (max_buffer_size,), dtype=diagonals.dtype, device=diagonals.device
    )

    nnz_offsets_tensor = torch.tensor(
        nnz_offsets[:-1], dtype=torch.int64, device=diagonals.device
    )

    # Launch kernel
    BLOCK_SIZE = 256
    grid = (num_diags * triton.cdiv(diag_len, BLOCK_SIZE),)

    diagonals_contig = diagonals.contiguous()
    offsets_contig = offsets.contiguous()

    with torch_device_fn.device(diagonals.device):
        _spdiags_kernel[grid](
            diagonals_contig,
            offsets_contig,
            indices_row_buffer,
            indices_col_buffer,
            values_buffer,
            nnz_offsets_tensor,
            num_diags,
            diag_len,
            nrows,
            ncols,
            BLOCK_SIZE=BLOCK_SIZE,
        )

    # Extract valid entries
    indices_list_row = []
    indices_list_col = []
    values_list = []

    for i in range(num_diags):
        if nnz_per_diag[i] > 0:
            start_idx = nnz_offsets[i]
            end_idx = start_idx + nnz_per_diag[i]
            indices_list_row.append(indices_row_buffer[start_idx:end_idx])
            indices_list_col.append(indices_col_buffer[start_idx:end_idx])
            values_list.append(values_buffer[start_idx:end_idx])

    indices_row = torch.cat(indices_list_row, dim=0)
    indices_col = torch.cat(indices_list_col, dim=0)
    indices = torch.stack([indices_row, indices_col], dim=0)
    values = torch.cat(values_list, dim=0)

    return torch.sparse_coo_tensor(
        indices, values, size=shape, dtype=diagonals.dtype, device=diagonals.device
    )
