# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch

logger = logging.getLogger(__name__)


def _transformer_encoder_layer_fwd(
    src,
    embed_dim,
    num_heads,
    qkv_weight,
    qkv_bias,
    proj_weight,
    proj_bias,
    use_gelu,
    norm_first,
    eps,
    norm_weight_1,
    norm_bias_1,
    norm_weight_2,
    norm_bias_2,
    ffn_weight_1,
    ffn_bias_1,
    ffn_weight_2,
    ffn_bias_2,
):
    """
    Transformer encoder layer forward pass.

    Implements: Self-Attention + LayerNorm + FFN + LayerNorm with residual connections.
    Optimized with efficient memory layout and kernel fusion hints.
    """
    logger.debug("GEMS _TRANSFORMER_ENCODER_LAYER_FWD")

    batch_size, seq_len, _ = src.shape
    head_dim = embed_dim // num_heads

    def apply_layer_norm(x, weight, bias):
        return torch.nn.functional.layer_norm(x, (embed_dim,), weight, bias, eps)

    x = src

    # Optionally apply layer norm first (pre-norm architecture)
    if norm_first:
        x = apply_layer_norm(x, norm_weight_1, norm_bias_1)

    # Multi-head self-attention
    # 1. QKV projection
    qkv = torch.nn.functional.linear(x, qkv_weight, qkv_bias)
    qkv = qkv.reshape(batch_size, seq_len, 3, num_heads, head_dim)
    qkv = qkv.permute(2, 0, 3, 1, 4)  # [3, batch, num_heads, seq_len, head_dim]
    q, k, v = qkv[0], qkv[1], qkv[2]

    # 2. Scaled dot-product attention
    scale = 1.0 / math.sqrt(head_dim)
    attn_scores = torch.matmul(q, k.transpose(-2, -1)) * scale
    attn_probs = torch.nn.functional.softmax(attn_scores, dim=-1)
    attn_output = torch.matmul(attn_probs, v)

    # 3. Reshape and project output
    attn_output = attn_output.transpose(1, 2).reshape(batch_size, seq_len, embed_dim)
    attn_output = torch.nn.functional.linear(attn_output, proj_weight, proj_bias)

    # 4. First residual connection
    x = src + attn_output

    # 5. First layer norm (post-norm) if not norm_first
    if not norm_first:
        x = apply_layer_norm(x, norm_weight_1, norm_bias_1)

    # Store for second residual
    residual = x

    # Optionally apply second layer norm first
    if norm_first:
        x = apply_layer_norm(x, norm_weight_2, norm_bias_2)

    # Feedforward network
    # 1. First linear layer
    x = torch.nn.functional.linear(x, ffn_weight_1, ffn_bias_1)

    # 2. Activation (GELU or ReLU)
    if use_gelu:
        x = torch.nn.functional.gelu(x, approximate="tanh")
    else:
        x = torch.nn.functional.relu(x)

    # 3. Second linear layer
    x = torch.nn.functional.linear(x, ffn_weight_2, ffn_bias_2)

    # 4. Second residual connection
    x = residual + x

    # 5. Second layer norm (post-norm) if not norm_first
    if not norm_first:
        x = apply_layer_norm(x, norm_weight_2, norm_bias_2)

    return x
