# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.ops.conv2d import conv2d_forward_kernel, conv2d_output_size
from flag_gems.ops.conv3d import conv3d
from flag_gems.ops.conv_transpose1d import conv_transpose1d
from flag_gems.ops.conv_transpose2d import conv_transpose2d
from flag_gems.utils import libentry  # noqa: F401  (kept for parity with conv ops)

logger = logging.getLogger(__name__)

# tl.dot requires the contraction dim K >= 16. The im2col matmul contracts over
# the (padded) per-group input channel count, so channels are padded up to this.
_MIN_DOT_K = 16


def _pair(value):
    if isinstance(value, (list, tuple)):
        if len(value) == 1:
            return int(value[0]), int(value[0])
        return int(value[0]), int(value[1])
    return int(value), int(value)


def _conv2d_forward(input, weight, bias, stride, padding, dilation, groups):
    """2D forward convolution driven directly by the Triton im2col kernel."""
    stride_height, stride_width = _pair(stride)
    padding_height, padding_width = _pair(padding)
    dilation_height, dilation_width = _pair(dilation)

    in_n, _, input_height, input_width = input.shape
    out_c, weight_c, weight_height, weight_width = weight.shape

    # Pad channels to satisfy the tl.dot K >= 16 constraint.
    if weight_c < _MIN_DOT_K:
        pad_c = _MIN_DOT_K - weight_c
        if groups == 1:
            input = torch.nn.functional.pad(input, (0, 0, 0, 0, 0, pad_c))
        else:
            N, C, H, W = input.shape
            input = input.reshape(N, groups, weight_c, H, W)
            input = torch.nn.functional.pad(input, (0, 0, 0, 0, 0, pad_c))
            input = input.reshape(N, groups * (weight_c + pad_c), H, W)
        weight = torch.nn.functional.pad(weight, (0, 0, 0, 0, 0, pad_c))
        weight_c = weight_c + pad_c

    out_height = conv2d_output_size(
        input_height, weight_height, stride_height, padding_height, dilation_height
    )
    out_width = conv2d_output_size(
        input_width, weight_width, stride_width, padding_width, dilation_width
    )

    output_dtype = input.dtype
    output = torch.empty(
        (in_n, out_c, out_height, out_width),
        device=input.device,
        dtype=output_dtype,
    )

    grid = lambda META: (  # noqa: E731
        triton.cdiv(in_n * out_height * out_width, META["BLOCK_NI_HO_WO"]),
        triton.cdiv(int(out_c // groups), META["BLOCK_CO"]),
        groups,
    )

    if bias is None:
        bias_pointer = torch.zeros(out_c, device=input.device, dtype=output_dtype)
    else:
        bias_pointer = bias

    conv2d_forward_kernel[grid](
        input,
        weight,
        output,
        bias_pointer,
        in_n,
        input_height,
        input_width,
        out_c,
        out_height,
        out_width,
        *input.stride(),
        *weight.stride(),
        *output.stride(),
        weight_c,
        weight_height,
        weight_width,
        stride_height,
        stride_width,
        padding_height,
        padding_width,
        dilation_height,
        dilation_width,
        groups=groups,
    )
    return output


def _convolution_overrideable_impl(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
):
    """Generic convolution dispatch backed by FlagGems Triton conv kernels.

    Mirrors ``aten::convolution_overrideable``: the spatial rank is inferred
    from ``weight.ndim - 2`` and the call is routed to the matching FlagGems
    Triton implementation.
    """
    spatial_dims = weight.ndim - 2
    assert spatial_dims in (1, 2, 3), (
        f"convolution_overrideable only supports 1D/2D/3D convolutions, "
        f"received weight with shape {tuple(weight.shape)}"
    )

    if transposed:
        if spatial_dims == 1:
            return conv_transpose1d(
                input, weight, bias, stride, padding, output_padding, groups, dilation
            )
        if spatial_dims == 2:
            return conv_transpose2d(
                input, weight, bias, stride, padding, output_padding, groups, dilation
            )
        raise NotImplementedError(
            "convolution_overrideable does not support 3D transposed convolution."
        )

    if spatial_dims == 1:
        # Reuse the 2D Triton kernel by promoting the single spatial axis.
        stride_w = _pair(stride)[0]
        padding_w = _pair(padding)[0]
        dilation_w = _pair(dilation)[0]
        return _conv2d_forward(
            input.unsqueeze(-1),
            weight.unsqueeze(-1),
            bias,
            (stride_w, 1),
            (padding_w, 0),
            (dilation_w, 1),
            groups,
        ).squeeze(-1)
    if spatial_dims == 2:
        return _conv2d_forward(input, weight, bias, stride, padding, dilation, groups)
    return conv3d(input, weight, bias, stride, padding, dilation, groups)


def convolution_overrideable(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
):
    logger.debug("GEMS CONVOLUTION_OVERRIDEABLE")
    return _convolution_overrideable_impl(
        input,
        weight,
        bias,
        stride,
        padding,
        dilation,
        transposed,
        output_padding,
        groups,
    )


def convolution_overrideable_out(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    *,
    out,
):
    logger.debug("GEMS CONVOLUTION_OVERRIDEABLE_OUT")
    result = _convolution_overrideable_impl(
        input,
        weight,
        bias,
        stride,
        padding,
        dilation,
        transposed,
        output_padding,
        groups,
    )
    out.copy_(result)
    return out
