# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import contextlib
import logging

import torch

logger = logging.getLogger(__name__)


@contextlib.contextmanager
def _full_precision_matmul():
    # This op leans on torch's conv_transpose2d / bmm for the gradient math. Called
    # directly those resolve to cuDNN / cuBLAS, which on Ampere-and-later default to
    # TF32 (10-bit mantissa) for fp32 GEMMs -- enough to blow past the fp32 backward
    # tolerance, since grad_weight sums N * Ho * Wo terms. FlagGems' own Triton
    # matmul kernels always pass allow_tf32=False, so pin the eager path to the same
    # full-precision contract here and restore the caller's flags on exit. Under
    # use_gems() the inner ops re-dispatch to those Triton kernels, so this guard is
    # a harmless no-op.
    prev_matmul = torch.backends.cuda.matmul.allow_tf32
    prev_cudnn = torch.backends.cudnn.allow_tf32
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False
    try:
        yield
    finally:
        torch.backends.cuda.matmul.allow_tf32 = prev_matmul
        torch.backends.cudnn.allow_tf32 = prev_cudnn


def _compute_bias_grad(out_grad, out_channels, dtype):
    # out_grad: [N, C, H, W]. grad_bias[c] = sum over n, h, w of out_grad[n, c, h, w].
    # A plain reduction over the batch and spatial axes; torch's reduction (or the
    # gems sum kernel under use_gems()) already accumulates in fp32, which both
    # keeps the C-length result accurate and beats the former per-channel Triton
    # loop that serialized the N * H * W reduction one output channel at a time.
    del out_channels
    return out_grad.to(torch.float32).sum(dim=(0, 2, 3)).to(dtype)


def _conv2d_grad_input(
    out_grad, weight, input_shape, stride, padding, dilation, groups
):
    # grad_input is exactly the transposed convolution of out_grad by the same
    # weight: d/d input of conv2d(input, weight) is conv_transpose2d(grad, weight).
    # conv_transpose2d is a first-class FlagGems operator, so calling it here keeps
    # the whole path on the tuned conv/GEMM kernels (a real Triton kernel under
    # use_gems(), cuDNN when the op is invoked directly) instead of the former
    # hand-rolled full-correlation kernel, whose per-output-pixel loop dominated
    # latency on the large-spatial-size cases.
    #
    # A plain stride-s transpose enlarges the output to
    #   (Ho - 1) * s - 2p + d * (k - 1) + 1,
    # which can fall short of the true input size when stride > 1 truncated the
    # forward output; output_padding makes up exactly that difference so the
    # returned gradient matches input_shape element-for-element.
    out_channels, weight_c, weight_height, weight_width = weight.shape
    in_n, in_channels, input_height, input_width = input_shape

    stride_height, stride_width = stride
    padding_height, padding_width = padding
    dilation_height, dilation_width = dilation

    out_height, out_width = out_grad.shape[2], out_grad.shape[3]
    base_height = (
        (out_height - 1) * stride_height
        - 2 * padding_height
        + dilation_height * (weight_height - 1)
        + 1
    )
    base_width = (
        (out_width - 1) * stride_width
        - 2 * padding_width
        + dilation_width * (weight_width - 1)
        + 1
    )
    output_padding = (input_height - base_height, input_width - base_width)

    grad_input = torch.nn.functional.conv_transpose2d(
        out_grad,
        weight,
        None,
        stride,
        padding,
        output_padding,
        groups,
        dilation,
    )
    return grad_input


def _conv2d_grad_weight(
    out_grad, input, weight_shape, stride, padding, dilation, groups
):
    # grad_weight[co, ci, kh, kw] = sum over (n, ho, wo) of
    #   out_grad[n, co, ho, wo] * input_patch[n, ci, kh, kw, ho, wo].
    # This is an im2col matmul: gather the input's receptive-field patches into
    # columns [N, Cin_g*kH*kW, Ho*Wo], then contract the Ho*Wo (and N) axes
    # against the output gradient [N, Cout_g, Ho*Wo] with a batched matmul and
    # sum the per-sample results over N. This hands the heavy reduction to a
    # tensor-core GEMM instead of the shared conv2d weight-gradient kernel, whose
    # per-output-pixel loop is orders of magnitude slower on large spatial sizes.
    #
    # The patches are materialized with as_strided (a pure view) rather than
    # torch.nn.functional.unfold: unfold would re-dispatch through FlagGems'
    # im2col kernel while this op runs under use_gems(), so keeping the gather as
    # a view sidesteps that and only bmm is delegated to a Triton kernel.
    out_channels, weight_c, weight_height, weight_width = weight_shape
    out_c = out_channels // groups
    in_n = input.shape[0]
    out_height, out_width = out_grad.shape[2], out_grad.shape[3]

    stride_height, stride_width = stride
    padding_height, padding_width = padding
    dilation_height, dilation_width = dilation

    out_grad = out_grad.contiguous()
    # Zero-pad the spatial dims up front so the strided patch gather stays fully
    # in-bounds; explicit padding also lets as_strided express the receptive
    # field with a simple stride pattern.
    if padding_height > 0 or padding_width > 0:
        input = torch.nn.functional.pad(
            input, (padding_width, padding_width, padding_height, padding_height)
        )
    input = input.contiguous()
    n_stride, c_stride, h_stride, w_stride = input.stride()

    spatial = out_height * out_width

    def _grad_weight_group(input_g, grad_g):
        # input_g: [N, Cin_g, Hpad, Wpad]; grad_g: [N, Cout_g, Ho, Wo].
        # Patches shape [N, Cin_g, kH, kW, Ho, Wo]: kernel taps advance by the
        # dilation, output positions advance by the stride.
        cols = torch.as_strided(
            input_g,
            (in_n, weight_c, weight_height, weight_width, out_height, out_width),
            (
                n_stride,
                c_stride,
                h_stride * dilation_height,
                w_stride * dilation_width,
                h_stride * stride_height,
                w_stride * stride_width,
            ),
        ).reshape(in_n, weight_c * weight_height * weight_width, spatial)
        grad_flat = grad_g.reshape(in_n, out_c, spatial)

        if input_g.dtype in (torch.float16, torch.bfloat16):
            # Fuse the N and Ho*Wo axes into a single contraction dimension and do
            # ONE matmul: [Cout_g, N*Ho*Wo] @ [N*Ho*Wo, Cin_g*kH*kW]. The GEMM
            # accumulates every term in its fp32 accumulator and rounds the result
            # to the input dtype exactly once. A per-sample bmm would instead round
            # each of the N partials to fp16/bf16 before summing them, and that
            # intermediate rounding drifts past the backward tolerance; the older
            # fix promoted both operands to fp32, which was accurate but paid for a
            # full fp32 copy of the (large) im2col tensor. The fused GEMM keeps the
            # operands in their native dtype, so it is both accurate and avoids that
            # materialization.
            a = grad_flat.transpose(0, 1).reshape(out_c, in_n * spatial)
            b = cols.transpose(0, 1).reshape(
                weight_c * weight_height * weight_width, in_n * spatial
            )
            weight_group = torch.mm(a, b.transpose(0, 1))
            return weight_group.to(torch.float32).reshape(
                out_c, weight_c, weight_height, weight_width
            )

        # fp32 (and wider): the operands already carry full precision and each
        # bmm contraction over Ho*Wo accumulates in fp32, so a per-sample batched
        # matmul followed by a fp32 sum over N is both accurate and faster here
        # than the single thin (M = Cout_g) GEMM above.
        # [N, Cout_g, Ho*Wo] @ [N, Ho*Wo, Cin_g*kH*kW] -> [N, Cout_g, Cin_g*kH*kW].
        per_sample = torch.bmm(grad_flat, cols.transpose(1, 2))
        return (
            per_sample.to(torch.float32)
            .sum(0)
            .reshape(out_c, weight_c, weight_height, weight_width)
        )

    if groups == 1:
        weight_back = _grad_weight_group(input, out_grad)
        return weight_back.to(torch.float32)

    # Grouped conv: each group owns a contiguous slice of the input channels and
    # output-gradient channels; accumulate their weight gradients independently.
    parts = []
    for gi in range(groups):
        input_g = input[:, gi * weight_c : (gi + 1) * weight_c]
        grad_g = out_grad[:, gi * out_c : (gi + 1) * out_c]
        parts.append(_grad_weight_group(input_g, grad_g))
    weight_back = torch.cat(parts, dim=0).contiguous()
    return weight_back.to(torch.float32)


def _normalize_pair(value):
    if isinstance(value, (list, tuple)):
        if len(value) == 1:
            return (int(value[0]), int(value[0]))
        return (int(value[0]), int(value[1]))
    return (int(value), int(value))


def convolution_backward_overrideable(
    grad_output,
    input,
    weight,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    output_mask,
):
    logger.debug("GEMS CONVOLUTION_BACKWARD_OVERRIDEABLE")
    assert not transposed, "convolution_backward_overrideable: transposed not supported"
    assert (
        input.ndim == 4 and weight.ndim == 4
    ), "convolution_backward_overrideable currently supports 2D convolution only"

    stride = _normalize_pair(stride)
    padding = _normalize_pair(padding)
    dilation = _normalize_pair(dilation)
    groups = int(groups)

    grad_input = None
    grad_weight = None
    grad_bias = None

    with _full_precision_matmul():
        if output_mask[0]:
            grad_input = _conv2d_grad_input(
                grad_output, weight, input.shape, stride, padding, dilation, groups
            ).to(input.dtype)
        if output_mask[1]:
            grad_weight = _conv2d_grad_weight(
                grad_output, input, weight.shape, stride, padding, dilation, groups
            ).to(weight.dtype)
        if output_mask[2]:
            grad_bias = _compute_bias_grad(
                grad_output, weight.shape[0], grad_output.dtype
            )

    return grad_input, grad_weight, grad_bias


def convolution_backward_overrideable_out(
    grad_output,
    input,
    weight,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    output_mask,
    out0,
    out1,
    out2,
):
    logger.debug("GEMS CONVOLUTION_BACKWARD_OVERRIDEABLE OUT")
    grad_input, grad_weight, grad_bias = convolution_backward_overrideable(
        grad_output,
        input,
        weight,
        stride,
        padding,
        dilation,
        transposed,
        output_padding,
        groups,
        output_mask,
    )
    if grad_input is not None:
        out0.copy_(grad_input)
    if grad_weight is not None:
        out1.copy_(grad_weight)
    if grad_bias is not None:
        out2.copy_(grad_bias)
    return out0, out1, out2
